# Generated by Django 5.0.2 on 2024-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lastmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.URLField(null=True)),
                ('quality', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('image_imbd', models.URLField(null=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='core.tag_s')),
            ],
        ),
    ]
