# Generated by Django 5.0.2 on 2024-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='moviess',
            field=models.FileField(default=22, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
