# Generated by Django 5.0.2 on 2024-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_movie_movie_moviess'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(default=22, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
