# Generated by Django 5.0.2 on 2024-02-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
