# Generated by Django 5.0.2 on 2024-02-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='subject',
        ),
    ]
